//
// ErrorModelErrorContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorModelErrorContext: Codable, JSONEncodable, Hashable {

    public var date: [String]

    public init(date: [String]) {
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
    }
}

