//
// ErrorModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorModelError: Codable, JSONEncodable, Hashable {

    public var code: String
    public var message: String
    public var context: ErrorModelErrorContext

    public init(code: String, message: String, context: ErrorModelErrorContext) {
        self.code = code
        self.message = message
        self.context = context
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case message
        case context
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
        try container.encode(context, forKey: .context)
    }
}

