//
// NewsListPagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewsListPagination: Codable, JSONEncodable, Hashable {

    public var limit: Double
    public var offset: Double
    public var count: Double
    public var total: Double

    public init(limit: Double, offset: Double, count: Double, total: Double) {
        self.limit = limit
        self.offset = offset
        self.count = count
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case offset
        case count
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
        try container.encode(count, forKey: .count)
        try container.encode(total, forKey: .total)
    }
}

