//
// NewsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NewsList: Codable, JSONEncodable, Hashable {

    public var pagination: NewsListPagination
    public var data: [NewsListDataInner]

    public init(pagination: NewsListPagination, data: [NewsListDataInner]) {
        self.pagination = pagination
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(data, forKey: .data)
    }
}

